/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interzaflog;

/**
 *
 * @author Jorge
 */
public class Log extends javax.swing.JFrame {

    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonInSes = new javax.swing.JButton();
        jPasswordFieldInSes = new javax.swing.JPasswordField();
        jTextFieldNombreInSes = new javax.swing.JTextField();
        jLabelContraseñaInSes = new javax.swing.JLabel();
        jLabelNombreInSes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInSes.setBackground(new java.awt.Color(204, 204, 204));
        jButtonInSes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonInSes.setText("Iniciar Sesion");
        jButtonInSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInSesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 430, 70));

        jPasswordFieldInSes.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordFieldInSes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldInSes.setText("jPasswordField1");
        jPanel1.add(jPasswordFieldInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 240, 50));

        jTextFieldNombreInSes.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombreInSes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNombreInSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreInSesActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 240, 50));

        jLabelContraseñaInSes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelContraseñaInSes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseñaInSes.setText("Contraseña:");
        jPanel1.add(jLabelContraseñaInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 50));

        jLabelNombreInSes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombreInSes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreInSes.setText("Nombre de Usuario:");
        jPanel1.add(jLabelNombreInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/interzaflog/FondoFinal.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInSesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInSesActionPerformed

    private void jTextFieldNombreInSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreInSesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreInSesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInSes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContraseñaInSes;
    private javax.swing.JLabel jLabelNombreInSes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldInSes;
    private javax.swing.JTextField jTextFieldNombreInSes;
    // End of variables declaration//GEN-END:variables
}
