/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interzaflog;

/**
 *
 * @author Jorge
 */
public class Reg extends javax.swing.JFrame {

    /**
     * Creates new form Reg
     */
    public Reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonReg = new javax.swing.JButton();
        jPasswordFieldReg = new javax.swing.JPasswordField();
        jLabelContraseñaReg = new javax.swing.JLabel();
        jLabelNombreInSes = new javax.swing.JLabel();
        jTextFieldNombreInSes = new javax.swing.JTextField();
        jTextFieldNombreInSes1 = new javax.swing.JTextField();
        jLabelNombreInSes1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReg.setBackground(new java.awt.Color(204, 204, 204));
        jButtonReg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonReg.setText("Registrarse");
        jButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 430, 70));

        jPasswordFieldReg.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldReg.setText("jPasswordField1");
        jPanel1.add(jPasswordFieldReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 240, 50));

        jLabelContraseñaReg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelContraseñaReg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseñaReg.setText("Contraseña:");
        jPanel1.add(jLabelContraseñaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 50));

        jLabelNombreInSes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombreInSes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreInSes.setText("Correo Electronico:");
        jPanel1.add(jLabelNombreInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 50));

        jTextFieldNombreInSes.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombreInSes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNombreInSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreInSesActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreInSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 240, 50));

        jTextFieldNombreInSes1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombreInSes1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNombreInSes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreInSes1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreInSes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 240, 50));

        jLabelNombreInSes1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombreInSes1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreInSes1.setText("Nombre de Usuario:");
        jPanel1.add(jLabelNombreInSes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/interzaflog/FondoFinal.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegActionPerformed

    private void jTextFieldNombreInSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreInSesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreInSesActionPerformed

    private void jTextFieldNombreInSes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreInSes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreInSes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContraseñaReg;
    private javax.swing.JLabel jLabelNombreInSes;
    private javax.swing.JLabel jLabelNombreInSes1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldReg;
    private javax.swing.JTextField jTextFieldNombreInSes;
    private javax.swing.JTextField jTextFieldNombreInSes1;
    // End of variables declaration//GEN-END:variables
}
